import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import{ ThemeProvider } from 'next-themes'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "porto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <html lang="en" suppressHydrationWarning>
          <body>
            <ThemeProvider 
              themeProps={{
                enableSystem: true,
                storageKey: "theme",
                defaultTheme: "system",
                attribute: "class",
                enableColorScheme: false,
              }}
            >
              {children}
            </ThemeProvider>
          </body>
        </html>
        
  );
}
